import {StyleSheet} from "react-native";


const styles = StyleSheet.create({
    flex: {flex: 1},
    flexColumn: {flexDirection: 'column'},
    flexRow: {flexDirection: 'row'},

    alignCenter: {alignItems: 'center'},
    alignStart: {alignItems: 'flex-start'},
    alignEnd: {alignItems: 'flex-end'},

    justifyCenter: {justifyContent: 'center'},
    justifyStart: {justifyContent: 'flex-start'},
    justifyEnd: {justifyContent: 'flex-end'},

    justifyCenter_alignCenter: {justifyContent: 'center', alignItems: 'center'},
    justifyCenter_alignStart: {justifyContent: 'center', alignItems: 'flex-start'},
    justifyCenter_alignEnd: {justifyContent: 'center', alignItems: 'flex-end'},

    justifyStart_alignCenter: {justifyContent: 'flex-start', alignItems: 'center'},
    justifyStart_alignStart: {justifyContent: 'flex-start', alignItems: 'flex-start'},
    justifyStart_alignEnd: {justifyContent: 'flex-start', alignItems: 'flex-end'},

    justifyEnd_alignCenter: {justifyContent: 'flex-end', alignItems: 'center'},
    justifyEnd_alignStart: {justifyContent: 'flex-end', alignItems: 'flex-start'},
    justifyEnd_alignEnd: {justifyContent: 'flex-end', alignItems: 'flex-end'},

    textCenter: {textAlign: 'center'},
    textLeft: {textAlign: 'left'},
    textRight: {textAlign: 'right'},

    textNone: {textDecorationLine: 'none'},
    textNormal: {fontWeight: 'normal'},
    textBold: {fontWeight: 'bold'},
    textItalic: {fontStyle: 'italic'},
    textUnderline: {textDecorationLine: 'underline'},
    textLineThrough: {textDecorationLine: 'line-through'},

    textSize12: {fontSize: 12},
    textSize18: {fontSize: 18},
    textSize24: {fontSize: 24},
    textSize30: {fontSize: 30},
    textSize36: {fontSize: 36},
    textSize42: {fontSize: 42},
    textSize48: {fontSize: 48},

    textRed: {color: 'red'},
    textBlue: {color: 'blue'},
    textGreen: {color: 'green'},
    textWhite: {color: 'white'},
    textBlack: {color: 'black'},
    textGray: {color: 'gray'},
    textLightGray: {color: 'lightgray'},

    p0: {padding: 0},
    p6: {padding: 6},
    p12: {padding: 12},
    p18: {padding: 18},
    p24: {padding: 24},
    p30: {padding: 30},

    m0: {margin: 0},
    m6: {margin: 6},
    m12: {margin: 12},
    m18: {margin: 18},
    m24: {margin: 24},
    m30: {margin: 30},

    wh100: {width: '100%', height: '100%'},
    wh95: {width: '95%', height: '95%'},
    wh90: {width: '90%', height: '90%'},
    wh85: {width: '85%', height: '85%'},
    wh80: {width: '80%', height: '80%'},
    wh75: {width: '75%', height: '75%'},
    wh70: {width: '70%', height: '70%'},
    wh65: {width: '65%', height: '65%'},
    wh60: {width: '60%', height: '60%'},
    wh55: {width: '55%', height: '55%'},
    wh50: {width: '50%', height: '50%'},
    wh45: {width: '45%', height: '45%'},
    wh40: {width: '40%', height: '40%'},
    wh35: {width: '35%', height: '35%'},
    wh30: {width: '30%', height: '30%'},
    wh25: {width: '25%', height: '25%'},
    wh20: {width: '20%', height: '20%'},
    wh15: {width: '15%', height: '15%'},
    wh10: {width: '10%', height: '10%'},
    wh5: {width: '5%', height: '5%'},

    h100: {height: '100%'},
    h95: {height: '95%'},
    h90: {height: '90%'},
    h85: {height: '85%'},
    h80: {height: '80%'},
    h75: {height: '75%'},
    h70: {height: '70%'},
    h65: {height: '65%'},
    h60: {height: '60%'},
    h55: {height: '55%'},
    h50: {height: '50%'},
    h45: {height: '45%'},
    h40: {height: '40%'},
    h35: {height: '35%'},
    h30: {height: '30%'},
    h25: {height: '25%'},
    h20: {height: '20%'},
    h15: {height: '15%'},
    h10: {height: '10%'},
    h5: {height: '5%'},

    w100: {width: '100%'},
    w95: {width: '95%'},
    w90: {width: '90%'},
    w85: {width: '85%'},
    w80: {width: '80%'},
    w75: {width: '75%'},
    w70: {width: '70%'},
    w65: {width: '65%'},
    w60: {width: '60%'},
    w55: {width: '55%'},
    w50: {width: '50%'},
    w45: {width: '45%'},
    w40: {width: '40%'},
    w35: {width: '35%'},
    w30: {width: '30%'},
    w25: {width: '25%'},
    w20: {width: '20%'},
    w15: {width: '15%'},
    w10: {width: '10%'},
    w5: {width: '5%'},

    bgRed: {backgroundColor: 'red'},
    bgBlue: {backgroundColor: 'blue'},
    bgGreen: {backgroundColor: 'green'},
    bgWhite: {backgroundColor: 'white'},
    bgBlack: {backgroundColor: 'black'},
    bgGray: {backgroundColor: 'gray'},
    bgLightGray: {backgroundColor: 'lightgray'},

    aspectRatio1: {aspectRatio: 1},
});

export default styles;